---
title: ""
---

 <!-- Dans le <head> --> <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">

<!-- Avant la balise </body> -->

```{=html}
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
```

```{=html}
<script>
  AOS.init();
</script>
```

::: {data-aos="fade-left" data-aos-offset="200" data-aos-easing="ease-in-sine" data-aos-duration="2000" data-aos-delay="500"}
L'Indonésie, en forme longue la république d'Indonésie (en indonésien Indonesia et Republik Indonesia) est un pays transcontinental situé principalement en Asie du Sud-Est, avec certaines parties de son territoire s’étendant en Océanie. Avec 17 000 îles, dont 922 habitées, il s'agit du plus grand archipel au monde. Dotée d’une population estimée à 285 millions de personnes, composée de plus de 600 groupes ethniques et parlant plus de 700 langues régionales, c'est le quatrième pays le plus peuplé au monde et le premier pays à majorité musulmane pour le nombre de croyants. Java, l’île la plus peuplée du monde, abrite plus de la moitié de la population du pays. L'Indonésie est une république dont la capitale est Jakarta. Une nouvelle capitale, nommée Nusantara, est en cours de développement pour la remplacer.
:::
